package eu.hydrologis.jgrass.gpsbabel.importwizard;

public interface GpsBabelConstants {
   @SuppressWarnings("nls")
   public final String[] formats =
        {"alantrl               Alan Map500 tracklogs (.trl)"
        ,"alanwpr               Alan Map500 waypoints and routes (.wpr)"
        ,"baroiq                Brauniger IQ Series Barograph Download"
        ,"cambridge             Cambridge/Winpilot glider software"
        ,"cst                   CarteSurTable data file"
        ,"cetus                 Cetus for Palm/OS"
        ,"coastexp              CoastalExplorer XML"
        ,"csv                   Comma separated values"
        ,"compegps              CompeGPS data files (.wpt/.trk/.rte)"
        ,"copilot               CoPilot Flight Planner for Palm/OS"
        ,"coto                  cotoGPS for Palm/OS"
        ,"axim_gpb              Dell Axim Navigation System (.gpb) file format"
        ,"an1                   DeLorme .an1 (drawing) file"
        ,"gpl                   DeLorme GPL"
        ,"saplus                DeLorme Street Atlas Plus"
        ,"saroute               DeLorme Street Atlas Route"
        ,"xmap                  DeLorme XMap HH Native .WPT"
        ,"xmap2006              DeLorme XMap/SAHH 2006 Native .TXT"
        ,"xmapwpt               DeLorme XMat HH Street Atlas USA .WPT (PPC)"
        ,"easygps               EasyGPS binary format"
        ,"igc                   FAI/IGC Flight Recorder Data Format"
        ,"gpssim                Franson GPSGate Simulation"
        ,"fugawi                Fugawi"
        ,"g7towin               G7ToWin data files (.g7t)"
        ,"garmin301             Garmin 301 Custom position and heartrate"
        ,"glogbook              Garmin Logbook XML"
        ,"gdb                   Garmin MapSource - gdb"
        ,"mapsource             Garmin MapSource - mps"
        ,"garmin_txt            Garmin MapSource - txt (tab delimited)"
        ,"pcx                   Garmin PCX5"
        ,"garmin_poi            Garmin POI database"
        ,"garmin_gpi            Garmin Points of Interest (.gpi)"
        ,"garmin                Garmin serial/USB protocol"
        ,"gtrnctr               Garmin Training Centerxml"
        ,"geo                   Geocaching.com .loc"
        ,"gcdb                  GeocachingDB for Palm/OS"
        ,"ggv_log               Geogrid Viewer tracklogs (.log)"
        ,"geonet                GEOnet Names Server (GNS)"
        ,"geoniche              GeoNiche .pdb"
        ,"kml                   Google Earth (Keyhole) Markup Language"
        ,"google                Google Maps XML"
        ,"gpilots               GpilotS"
        ,"gtm                   GPS TrackMaker"
        ,"arc                   GPSBabel arc filter file"
        ,"gpsdrive              GpsDrive Format"
        ,"gpsdrivetrack         GpsDrive Format for Tracks"
        ,"gpsman                GPSman"
        ,"gpspilot              GPSPilot Tracker for Palm/OS"
        ,"gpsutil               gpsutil"
        ,"gpx                   GPX XML"
        ,"hiketech              HikeTech"
        ,"holux                 Holux (gm-100) .wpo Format"
        ,"hsandv                HSA Endeavour Navigator export File"
        ,"html                  HTML Output"
        ,"ignrando              IGN Rando track files"
        ,"ktf2                  Kartex 5 Track File"
        ,"kwf2                  Kartex 5 Waypoint File"
        ,"kompass_tk            Kompass (DAV) Track (.tk)"
        ,"kompass_wp            Kompass (DAV) Waypoints (.wp)"
        ,"psitrex               KuDaTa PsiTrex text"
        ,"lowranceusr           Lowrance USR"
        ,"maggeo                Magellan Explorist Geocaching"
        ,"mapsend               Magellan Mapsend"
        ,"magnav                Magellan NAV Companion for Palm/OS"
        ,"magellanx             Magellan SD files (as for eXplorist)"
        ,"magellan              Magellan SD files (as for Meridian)"
        ,"magellan              Magellan serial protocol"
        ,"tef                   Map&Guide 'TourExchangeFormat' XML"
        ,"mag_pdb               Map&Guide to Palm/OS exported files (.pdb)"
        ,"mapconverter          Mapopolis.com Mapconverter CSV"
        ,"mxf                   MapTech Exchange Format"
        ,"msroute               Microsoft AutoRoute 2002 (pin/route reader)"
        ,"msroute               Microsoft Streets and Trips (pin/route reader)"
        ,"s_and_t               Microsoft Streets and Trips 2002-2006"
        ,"bcr                   Motorrad Routenplaner (Map&Guide) .bcr files"
        ,"psp                   MS PocketStreets 2002 Pushpin"
        ,"tpg                   National Geographic Topo .tpg (waypoints)"
        ,"tpo2                  National Geographic Topo 2.x .tpo"
        ,"tpo3                  National Geographic Topo 3.x/4.x .tpo"
        ,"navicache             Navicache.com XML"
        ,"nmn4                  Navigon Mobile Navigator .rte files"
        ,"dna                   Navitrak DNA marker format"
        ,"netstumbler           NetStumbler Summary File (text)"
        ,"nima                  NIMA/GNIS Geographic Names File"
        ,"nmea                  NMEA 0183 sentences"
        ,"ozi                   OziExplorer"
        ,"palmdoc               PalmDoc Output"
        ,"pathaway              PathAway Database for Palm/OS"
        ,"quovadis              Quovadis"
        ,"raymarine             Raymarine Waypoint File (.rwf)"
        ,"cup                   See You flight analysis data"
        ,"sportsim              Sportsim track files (part of zipped .ssz files)"
        ,"stmsdf                Suunto Trek Manager (STM) .sdf files"
        ,"stmwpp                Suunto Trek Manager (STM) WaypointPlus files"
        ,"openoffice            Tab delimited fields useful for OpenOffice, Plotic"
        ,"text                  Textual Output"
        ,"tomtom_itn            TomTom Itineraries (.itn)"
        ,"tomtom_asc            TomTom POI file (.asc)"
        ,"tomtom                TomTom POI file (.ov2)"
        ,"tmpro                 TopoMapPro Places File"
        ,"dmtlog                TrackLogs digital mapping (.trl)"
        ,"tiger                 U.S. Census Bureau Tiger Mapping Service"
        ,"unicsv                Universal csv with field structure in first line"
        ,"vcard                 Vcard Output (for iPod)"
        ,"vitosmt               Vito Navigator II tracks"
        ,"vitovtt               Vito SmartMap tracks (.vtt)"
        ,"wfff                  WiFiFoFum 2.0 for PocketPC XML"
        ,"wbt-bin               Wintec WBT-100/200 Binary File Format"
        ,"wbt                   Wintec WBT-100/200 GPS Download"
        ,"wbt-tk1               Wintec WBT-201/G-Rays 2 Binary File Format"
        ,"yahoo                 Yahoo Geocode API data"};

}
